### ISSUE TITLE
The road to v1

### ISSUE THREAD

**Issue by koba04** [teppeis/duck#282]
I think it's the time that we release v1. What do you think?

**Comment by teppeis** [comment]
@koba04 Yeah, it's time! How about transferring this repo to some organization?

**Comment by koba04** [comment]
It looks good for me 👍
What about `cybozu`? (Of course, I want you to stay the maintainer😄)

**Comment by koba04** [comment]
Let's work on this after #285 has been resolved.

**Comment by teppeis** [comment]
Before v1, I want to bump min version of google-closure-compiler in peerDeps.
https://github.com/teppeis/duck/blob/52feb8ca8d052399aee63826a81ce9f82b8cadb3/package.json#L61
https://github.com/teppeis/duck/blob/52feb8ca8d052399aee63826a81ce9f82b8cadb3/.circleci/config.yml#L23

No one uses `v20180101` now. 
`v20180910` is good for new min version. The version introduces `key` field in `--error_json` like `JSC_DEPRECATED_CLASS_REASON`.
