### ISSUE TITLE
Ignore compiler warnings

### ISSUE THREAD

**Issue by koba04** [teppeis/duck#285]
Currently, `duck build:js` ignores warnings of compiling.
But we have a case that we want to get the warnings.
I have two options for this.

1. Prints warnings to stderr using `console.error` https://github.com/koba04/duck/commit/622e593384ea111c74956e2a4373664bc334bfd6
1. Add `--strict` option that treats any warnings as errors https://github.com/koba04/duck/commit/59238d90d6f21b2164a3b20a50665a74b30c0956

We could combine the options, which means that if `--strict` option is disabled, warnings are printed to stderr.

@teppeis Do you have any ideas for this issue?

**Comment by teppeis** [comment]
@koba04 The two options have different purposes, so consider them separately.
Option 1 should be done.
But why do you need option 2? I think that the straight forward way is to make it an error with Compiler option `jscomp_error`.

**Comment by koba04** [comment]
@teppeis Thanks!

> But why do you need option 2? I think that the straight forward way is to make it an error with Compiler option jscomp_error.

Ah, that's right.
I should change warning categories to ERROR if I want to do option 2.
https://github.com/google/closure-compiler/wiki/Warnings#warnings-categories

Let's discuss option 1.

I've written a patch for this.
But I doubt that there is a better approach to this.

This patch prints warnings to stderr using `console.error`.
I've tried to use logger for this, but I couldn't do that because, without `nonTTY` mode,  logger output is collapsed by `listr` so we can't see the warnings.

**Comment by teppeis** [comment]
@koba04 There is a tricky way through logger. `--printConfig` uses this way.

1. [input](https://github.com/teppeis/duck/blob/ebb0eaf4b4d1bbef3978f44dae536a88a583bcf1/src/commands/buildJs.ts#L64-L72)
2. [store](https://github.com/teppeis/duck/blob/ebb0eaf4b4d1bbef3978f44dae536a88a583bcf1/src/cli.ts#L51-L61)
3. [output](https://github.com/teppeis/duck/blob/ebb0eaf4b4d1bbef3978f44dae536a88a583bcf1/src/cli.ts#L283)

But it's too complex and we need another solution.
I think it's enough that each command returns content and cli logic outputs it.

**Comment by teppeis** [comment]
I've pushed WIP to output warnings https://github.com/teppeis/duck/pull/296
